"""Added Student model

Revision ID: 4f040a87d345
Revises: 76e821d055cb
Create Date: 2024-09-12 21:10:15.984386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f040a87d345'
down_revision = '76e821d055cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
